version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-saas-lab1"
s3_bucket = "sam-bootstrap-bucket-ed196bc4-f79a-4582-9b59-283f56c043d8"
s3_prefix = "serverless-saas-lab1"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
cached="true"
parallel="true"
