version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-saas-fauna"
s3_bucket = "sam-bootstrap-bucket-3341a9d7-f94d-453c-9605-4dda23699cb2"
s3_prefix = "serverless-saas-fauna"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
cached="true"
parallel="true"
