# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

version: 0.2
phases:
  install:    
    commands:
      # Install packages or any pre-reqs in this phase.

  pre_build:
    commands:
      # Run tests, lint scripts or any other pre-build checks.

  build:
    commands:
      # Use Build phase to build your artifacts (compile, etc.)

      # Run Fauna migrations      
      - cd ../fauna_resources
      - npm install
      - node index.js

  post_build:
    commands:
      # Use Post-Build for notifications, git tags, upload artifacts to S3
