version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-saas-wkshp"
s3_bucket = "sam-bootstrap-bucket-751c65f9-1100-4c3d-9f45-2c9d457ff655"
s3_prefix = "serverless-saas-wkshp"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
cached="true"
parallel="true"
