# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Template to create dynamodb tables as part of bootstrap
Parameters:
  StackName:
    Type: String
Resources:
  ServerlessSaaSSettingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: settingName
          AttributeType: S
      KeySchema:
        - AttributeName: settingName
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub '${StackName}-Settings'
  TenantStackMappingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: tenantId
          AttributeType: S
      KeySchema:
        - AttributeName: tenantId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub '${StackName}-TenantStackMapping'
Outputs:
  ServerlessSaaSSettingsTableArn: 
    Value: !GetAtt ServerlessSaaSSettingsTable.Arn
  ServerlessSaaSSettingsTableName: 
    Value: !Ref ServerlessSaaSSettingsTable
  TenantStackMappingTableArn: 
    Value: !GetAtt TenantStackMappingTable.Arn
  TenantStackMappingTableName: 
    Value: !Ref TenantStackMappingTable
