version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-saas-wkshp"
s3_bucket = "sam-bootstrap-bucket-a4b87023-6feb-42d2-9828-aacce51b37b8"
s3_prefix = "serverless-saas-wkshp"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
cached="true"
parallel="true"
