version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stack-pooled-wkshp"
s3_bucket = "sam-bootstrap-bucket-34a11516-c234-4a0f-89e8-ed2cadb66e41"
s3_prefix = "serverless-saas-wkshp-tenant"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
cached="true"
parallel="true"
